version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
    - 10.3.0
  - dependency-name: ember-cli-babel
    versions:
    - 7.26.2
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.6.4
  - dependency-name: ember-router-scroll
    versions:
    - 4.0.0
    - 4.0.1
    - 4.0.2
